# -*- coding: utf-8 -*-
"""Revision1EdgeSandboxFuncBasedLRSVMLDAPCA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q4kP9TmLV5h-bZ5ijXPddhx4NrRw1dwz

##Notes

**Flow Rate MNP Analysis**

Nov 2024 - Lexi DeFord, Logistic Regression, LASSO (which is really logistic regression with L1 regularization)

March 2025 - LD; added LDA, SVM, fixed LRL1 (LASSO for classification)

March 2025 - LD; moved models into functions for serial processing

April 2025 - LD; Added plotting function and cleaned up functions, added flag to look at slope itself

(PCA in development)

July 30th 2025 - LD; Adding analysis of k and k diff values as well for an explainable model

August 2025 - LD; Forward and Backward Feature Selection via BIC+

Septemeber 2025 - LD; Grid Search with LR, LDA, and SVM_L and SVM_R

Into Spring 2026 - LD; top feature figures, biomolecule characteristics figures

June 2026 - LD; grouping by chip

## Setup


from google.auth import default
from googleapiclient.discovery import build
from googleapiclient import discovery

# 3. Google Colab specific imports
from google.colab.patches import cv2_imshow  # for image display in Colab

# 4. Google Sheets integration
import gspread as gs
from gspread.exceptions import APIError
import gspread_dataframe as gd

# 5. PyDrive2 setup with proper authentication
from pydrive2.auth import GoogleAuth
from pydrive2.drive import GoogleDrive

# 6. Get credentials and authorize gspread (separate from PyDrive2)
creds, _ = default()
gc = gs.authorize(creds)

# Create GoogleAuth instance
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)


from google.colab import drive as colab_drive
colab_drive.mount('/content/drive')
"""
from pathlib import Path
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import csv
import seaborn as sns
import sys
import re

import statistics as stat
from sklearn.linear_model import LassoCV, Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, mean_squared_error, r2_score, accuracy_score, classification_report, f1_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

from sklearn.svm import SVC
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegressionCV
from sklearn.linear_model import LogisticRegression
import warnings
from sklearn.exceptions import ConvergenceWarning
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.cluster import KMeans
from sklearn.metrics import adjusted_rand_score
#import shap

import xgboost as xgb
from itertools import combinations
from IPython.display import clear_output
def WrangleData(filePath, selectedPlasticsList=['MCH', 'MCM', 'MCL', "MSH", "MSM", "MSL", "SCH", "SCM", "SCL", "SSH", "SSM", "SSL", "LCH", "LCM", "LCL", "VCH", "VCM", "VCL", "4", "3", "2", "1", "TCH", "TCM", "TCL", "15", "16", "17", "18", "BCH", "BCM", "BCL", "25", "26", "27", "28", "CCH", "CCM", "CCL"],
                selectedNotPlasticsList = [], selectedReagentsList=[], selectedNotReagentsList=[], printFlag=True, slopeFlag=False):
  FitData = pd.read_csv(filePath, index_col=0)
  FitData.reset_index(0, inplace=True)
  dataFrame = FitData.copy()
  dataFrame["Plastic"] = dataFrame['Plastic'].astype(str)
  if printFlag:
    print(f'Input File Path: {filePath}')
    print(f'Selected Plastics to include: {selectedPlasticsList}')
    print(f'Selected Plastics to exclude: {selectedNotPlasticsList}')
    print(f'Selected Reagents to include: {selectedReagentsList}')
    print(f'Selected Reagents to exclude: {selectedNotReagentsList}')
    #dataFrame.head()
  if len(selectedReagentsList) > 0:
    dataFrame = dataFrame[dataFrame['Reagent'].isin(selectedReagentsList)]
  if len(selectedNotReagentsList) > 0:
    dataFrame = dataFrame[~dataFrame['Reagent'].isin(selectedNotReagentsList)]
  if len(selectedPlasticsList) > 0:
    dataFrame = dataFrame[dataFrame['Plastic'].isin(selectedPlasticsList)]
  if len(selectedNotPlasticsList) > 0:
    dataFrame = dataFrame[~dataFrame['Plastic'].isin(selectedNotPlasticsList)]
  if printFlag:
    print(f'Unique Plastics: {dataFrame["Plastic"].unique()}')
  if slopeFlag:
    dataFrameFull = pd.pivot_table(dataFrame, values='Slope', index=['Plastic', "Channel"], columns=['WindowEdge', 'Reagent'])
  else:
    dataFrameFull = pd.pivot_table(dataFrame, values='Adjusted_Slope', index=['Plastic', "Channel"], columns=['WindowEdge', 'Reagent'])
  df_Full_Flat = dataFrameFull
  df_Full_Flat.columns = ['_'.join(map(str, col)) for col in df_Full_Flat.columns]
  df_Full_Flat = df_Full_Flat.reset_index(0)
  df_Full_Flat = df_Full_Flat.reset_index(0)
  df_Full_Flat['Group_PN'] = df_Full_Flat['Plastic'].apply(lambda x: 'Plastic' if x[0] in ['M', 'S', 'L', 'T', 'V', 'B', 'C', 'N'] else 'Null')
  df_Full_Flat['Group_MSLVTN'] = df_Full_Flat['Plastic'].apply(
        lambda x: 'PMMA' if x[0] == "M" else ('PS' if x[0] == 'S' else ('LDPE' if x[0] == 'L' else ('PVC' if x[0] == 'V' else ('PET' if x[0] in ['T', 'B', 'C'] else 'Null'))))
  )
  df_Full_Flat['Group_Full'] = df_Full_Flat['Plastic'].apply(
        lambda x: x[0:2] if x[0] in ["M", "S", "L", "V", "T", "B", "C", "N"] else ('DI' if x in ["4", "3", "2", "1"] else ('BW1' if x in ["15", "16", "17", "18"] else ('BW2' if x in ["25", "26", "27", "28"] else np.nan)))
  )
  df_Full_Flat['Group_MHLN'] = df_Full_Flat['Plastic'].apply(
        lambda x: "Null" if x in ["4", "3", "2", "1", "15", "16", "17", "18", "25", "26", "27", "28"] else (
        'Medium' if x[2] == "M" else ('High' if x[2] == 'H' else ('Low' if x[2] == 'L' else np.nan)))
  )
  df_Full_Flat['Group_CSN'] = df_Full_Flat['Plastic'].apply(
      lambda x: "Null" if x in ["4", "3", "2", "1", "15", "16", "17", "18", "25", "26", "27", "28"] else (
      'Cryo' if x[1] == "C" else ("Spherical" if x[1] == 'S' else np.nan))
  )
  df_Full_Flat['Group_Null'] = df_Full_Flat['Plastic'].apply(
        lambda x: 'DI' if x in ["4", "3", "2", "1"] else ('BW1' if x in ["15", "16", "17", "18"] else ('BW2' if x in ["25", "26", "27", "28"] else np.nan))
  )
  if printFlag:
    display(df_Full_Flat)
    print(f"Unique Entries in Group_PN: {df_Full_Flat['Group_PN'].unique()}")
    print(f"Unique Entries in Group_MSLVTN: {df_Full_Flat['Group_MSLVTN'].unique()}")
    print(f"Unique Entries in Group_Full: {df_Full_Flat['Group_Full'].unique()}")
    print(f"Unique Entries in Group_MHL: {df_Full_Flat['Group_MHL'].unique()}")
    print(f"Unique Entries in Group_CS: {df_Full_Flat['Group_CS'].unique()}")
    print(f"Unique Entries in Group_Null: {df_Full_Flat['Group_Null'].unique()}")
  return df_Full_Flat
#-------------------------------------------------------------------------------
def PrepXY(group_name, df, testSize=0.2, randomState=42, encodeYFlag=True, standardizeFlag=True,
           printFlag=False, valFlag=False, valSize=0.4, dataType="Slope", df_test=None,
           chipSplit=False, testChipGroup=0):
    """
    channelSplit: if True, split by channel groups instead of random split
    testChannelGroup: which channel group to use as test set (0=ch0-3, 1=ch4-7, 2=ch8-11, 3=ch12-15)
    """
    data = df.dropna(subset=[group_name])

    if dataType == 'Slope':
        X = data[data.columns[2:-7]]
    elif dataType == 'k':
        X = data[data.columns[2:-6]]
    elif dataType == 'bic':
        cols = [col for col in df.columns if col not in [group_name]]
        X = data[cols]

    y = data[group_name]

    if printFlag:
        display(X)

    if encodeYFlag:
        le = LabelEncoder()
        y_orig = y
        y = le.fit_transform(y)

    # ── Channel-based split ──────────────────────────────────────────────────
    if chipSplit:
        channel_groups = [(0, 3), (4, 7), (8, 11), (12, 15)]
        lo, hi = channel_groups[testChipGroup]
        test_mask  = data['Channel'].between(lo, hi)
        train_mask = ~test_mask

        X_train = X[train_mask]
        X_test  = X[test_mask]
        y_train = y[train_mask] if not encodeYFlag else y[train_mask]
        y_test  = y[test_mask]  if not encodeYFlag else y[test_mask]

    # ── Explicit test dataframe provided ────────────────────────────────────
    elif df_test is not None and dataType == 'k':
        X_test  = df_test[df_test.columns[2:-6]]
        y_test  = le.fit_transform(df_test[group_name])
        X_train = data[df_test.columns[2:-6]]
        y_train = le.fit_transform(data[group_name])

    # ── Default random split ─────────────────────────────────────────────────
    else:
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=testSize, random_state=randomState
        )

    # ── Optional validation split ────────────────────────────────────────────
    if valFlag:
        X_train, X_val, y_train, y_val = train_test_split(
            X_train, y_train, test_size=valSize, random_state=randomState
        )
        if standardizeFlag:
            scaler = StandardScaler()
            X_train_scaled = scaler.fit_transform(X_train)
            X_test_scaled  = scaler.transform(X_test)
            X_val_scaled   = scaler.transform(X_val)
        return X_train, X_test, y_train, y_test, X_train_scaled, X_test_scaled, X, y, y_orig, le, X_val_scaled, X_val, y_val
    else:
        if standardizeFlag:
            scaler = StandardScaler()
            X_train_scaled = scaler.fit_transform(X_train)
            X_test_scaled  = scaler.transform(X_test)
        return X_train, X_test, y_train, y_test, X_train_scaled, X_test_scaled, X, y, y_orig, le
#-------------------------------------------------------------------------------
def GridSearchFeatureSelectionMaster(group_name, df_entire, model_list = ["LR", "SVM", "LDA"], min_features=2, max_features=17, combination_type='all',
                                randomState=42, dataType='k', save_csv_path="/content/drive/MyDrive/Lexi/MNP/ML_Analysis/20260624Rev1Save.csv",
                                printFlag=True, save_results=False,
                                result_filename=None, test_flag=False, kernelType='rbf',
                                swapLabel=False, chipSplit=False, chipGroup=0,
                                **model_kwargs):
    """ GridFeatureSelection runs a grid search for feature combinations. ChipGroup
    sorting for train/test split is inculded. """

    """
    for each model
        do feature selection
        for each data split (hold out 1 chip for test metric)
            for each validation data split (hold out 1 chip for validation metric)
                - run through all feature combos with two chips of train data, judge by validation chip
                - save top [feature set x validation metric]
            run model with top features, judge by test chip, save test metric
        average test metrics across all data splits
        sum number of times each feature set was selected
    """
    CSV_COLUMNS = ["m", "group_name", "mf", "hold_out_chip", "val_chip", "best_val", "best_features", "val_test", "kernel_type"]
    MODEL_FUNCTIONS = {
        'SVM': RunSVM,
        'LDA': RunLDA,
        'LR': RunLR,
    }
    if group_name == 'Group_PN':
        metric = 'f1_score'
        f1Flag=True
    elif group_name == 'Group_Full':
        metric = 'accuracy'
        f1Flag=False
    elif group_name == 'Group_MHLN':
        metric = 'accuracy'
        f1Flag = False
    max_features_list = list(range(min_features, max_features + 1))
    existing_results = load_existing_results(save_csv_path)
    print(f"Loaded {len(existing_results)} existing results from CSV")
    for m in model_list:
        model_func = MODEL_FUNCTIONS[m]
        for mf in max_features_list:
            for hold_out_chip in [0, 1, 2, 3]: #per hold out data split
                df, df_test = HoldOut(df_entire, chipGroup=hold_out_chip, printFlag=False)
                val_results_metric = []
                val_results_features = []
                for val_chip in [0, 1, 2, 3]: #per validation data split
                    #check if this m, group_name, hold_out_chip, val_chip line in save_csv_path is already written, if not, do this loop
                    if val_chip == hold_out_chip:
                        continue
                    key = (str(m), str(group_name), str(mf), str(hold_out_chip), str(val_chip), str(kernelType))
                    if key in existing_results:
                        print(f"Skipping {m} {group_name} mf={mf} hold_out={hold_out_chip} val={val_chip}, str={kernelType} (already done)")
                        continue
                    best_val, best_features = GridSearchFeatureSelection(group_name, df, model_func, mf, mf, val_chip=val_chip, kernelType=kernelType, printFlag=False)
                    val_results_metric.append(best_val)
                    val_results_features.append(best_features)
                    print(f"Best validation metric value for {m} {group_name} hold out ({hold_out_chip}) val ({val_chip}) : {best_val}")
                    print(f"Combined unique strings: {best_features}")
                    all_columns = df.columns.tolist()
                    groups_list = [item for item in all_columns if item.startswith("Group")]
                    total_col = list(["Channel", "Plastic"]) + best_features + groups_list
                    df_test_use = df_test[total_col].copy()
                    results = model_func(group_name = group_name, df = df, randomState=randomState,
                        dataType=dataType, printFlag=False, featureAnalysisFlag=False,
                        BICFlag=False, f1Flag=f1Flag, cmFlag=True, kernelType=kernelType,
                        swapLabel=False, df_test=df_test_use, chipSplit=None)
                    val_test = results[metric]
                    row = {
                        "Model": m,
                        "Group_Name": group_name,
                        "N_Features": mf,
                        "Hold_Chip": hold_out_chip,
                        "Val_Chip": val_chip,
                        "Best_Val": best_val,
                        "Features": best_features,
                        "Test_Metric": val_test,
                        "Kernel_Type": kernelType
                    }
                    write_result(save_csv_path, row)
                    existing_results.add(key)
                    #write to save_csv_path; save m, group_name, mf, hold_out_chip, val_chip, best_val, best_features, val_test
    return None
#-------------------------------------------------------------------------------
def load_existing_results(save_csv_path):
    """Load existing results as a set of (Model, Group_Name, Hold_Chip, Val_Chip) tuples."""
    existing = set()
    save_csv_path = Path(save_csv_path)
    if save_csv_path.exists():
        with save_csv_path.open("r", newline="", encoding="utf-8-sig") as f:
            content = f.read().strip()
            if not content:
                return existing
            f.seek(0)
            reader = csv.DictReader(f)
            for row in reader:
                existing.add((row["Model"], row["Group_Name"], row["Hold_Chip"], row["Val_Chip"], row["Kernel_Type"]))
    return existing
#-------------------------------------------------------------------------------
def write_result(save_csv_path, row_dict):
    """Append a single result row to the CSV, writing header if file is new."""
    save_csv_path = Path(save_csv_path)
    file_exists = save_csv_path.exists()
    with save_csv_path.open("a", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=list(row_dict.keys()))
        if not file_exists:
            writer.writeheader()
        writer.writerow(row_dict)
#-------------------------------------------------------------------------------
def MakeFeatureCombos(group_name, df, n_features_min, n_features_max):
    """ Outputs a list of feature combinations given min and max number of features. """
    all_columns = df.columns.tolist()
    feature_list_int = [item for item in all_columns if not item.startswith("Group")]
    feature_list = [item for item in feature_list_int if item not in set(['Plastic', 'Channel'])]
    feature_combos = []
    for size in list(range(n_features_min, n_features_max + 1)):
        feature_combos.extend(combinations(feature_list, size))
    return feature_combos
#-------------------------------------------------------------------------------
def GridSearchFeatureSelection(group_name, df, model_func, min_features, max_features,
                                val_chip, scoring='accuracy', randomState=42, dataType='k',
                                printFlag=False, plotFlag=False, save_results=False,
                                result_filename=None, test_flag=False, kernelType='rbf',
                                swapLabel=False, chipSplit=False, chipGroup=0,
                                **model_kwargs):
    """ MakeFeatureCombos"""
    #if there are ties, need to collect all features and average val metrics
    if group_name == 'Group_PN':
        metric = 'f1_score'
        f1Flag=True
    elif group_name == 'Group_Full':
        metric = 'accuracy'
        f1Flag=False
    elif group_name == 'Group_MHLN':
        metric = 'accuracy'
        f1Flag = False
    feature_combos = MakeFeatureCombos(group_name, df, min_features, max_features)
    all_columns = df.columns.tolist()
    group_list = [item for item in all_columns if item.startswith("Group")]
    total = len(feature_combos)
    print(f"Total number of features combos for this run is {total}")
    results_store = [None] * total
    for i, f in enumerate(feature_combos):
        selected_columns = list(dict.fromkeys(["Channel", "Plastic"] + list(f) + group_list))
        subset_df = df[selected_columns].copy()
        results = model_func(group_name = group_name, df = subset_df, randomState=randomState,
                dataType=dataType, printFlag=False, featureAnalysisFlag=True,
                BICFlag=False, f1Flag=f1Flag, cmFlag=False, kernelType=kernelType,
                swapLabel=False, df_test=None, chipSplit=False, chipGroup=val_chip)
        results_store[i] = (results[metric], f)
    # Sort by metric value (descending)
    results_store.sort(key=lambda x: x[0], reverse=True)

    # Find best metric value
    best_metric = results_store[0][0]

    # Collect all string lists with the best metric value
    best_strings = []
    for metric_val, string_list in results_store:
        if metric_val == best_metric:
            best_strings.extend(string_list)
        else:
            break  # sorted, so no need to continue
    seen = set()
    unique_best_strings = []
    for s in best_strings:
        if s not in seen:
            seen.add(s)
            unique_best_strings.append(s)
    return best_metric, unique_best_strings
#-------------------------------------------------------------------------------
def RunLR(group_name, df, printFlag=False, featureAnalysisFlag=False, residualsFlag=False, classificationReportFlag=False, randomState=42, cmFlag=False, f1Flag = False, swapLabel=False, dataType='Slope', BICFlag=False, kernelType=None, df_test=None, save_plot_name=None, recallFlag=False, chipSplit=False, chipGroup=0):
    results = {}
    X_train, X_test, y_train, y_test, X_train_scaled, X_test_scaled, X, y, y_orig, le = PrepXY(group_name, df, printFlag=printFlag, randomState=randomState, dataType=dataType, df_test=df_test, chipSplit=chipSplit,testChipGroup=chipGroup)
    if printFlag:
        print(X_train.columns[:20])
        print(f'Unique Y train values {np.unique(y_train, return_counts=True)}')
        print(f'Unique Y test values {np.unique(y_test, return_counts=True)}')
    model = LogisticRegression(solver='lbfgs', max_iter= 2000)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    if printFlag:
        print(f"Logistic Regression with {group_name}")
        print("Intercept:", model.intercept_)
        print("Classes:", le.classes_)
        print("Iterations:", model.n_iter_)
    if classificationReportFlag:
        print("Classification Report (LR):\n", classification_report(y_test, y_pred))
    accuracy = accuracy_score(y_test, y_pred)
    #print(f'accuracy is {accuracy}')
    results['accuracy'] = accuracy

    # Calculate BIC if requested
    if BICFlag:
        # Get predicted probabilities for log-likelihood calculation
        y_pred_proba = model.predict_proba(X_test)

        # Calculate log-likelihood
        log_likelihood = 0
        for i, true_label in enumerate(y_test):
            log_likelihood += np.log(y_pred_proba[i, true_label])

        # Calculate number of parameters for standard Logistic Regression
        # For binary classification: n_features + 1 (intercept)
        # For multiclass: n_features * n_classes + n_classes (intercepts)
        n_features = X_train.shape[1]
        n_classes = len(model.classes_)

        if n_classes == 2:
            # Binary classification: only one set of coefficients needed
            n_params = n_features + 1  # coefficients + intercept
        else:
            # Multiclass: coefficients and intercept for each class
            n_params = n_features * n_classes + n_classes

        n_samples = len(y_test)

        # Calculate BIC: -2 * log_likelihood + k * log(n)
        bic = -2 * log_likelihood + n_params * np.log(n_samples)
        results['bic'] = bic

        if printFlag:
            print(f"BIC of the LR model: {bic}")
            print(f"Number of parameters: {n_params}")
            if n_classes == 2:
                print(f"  - Coefficients: {n_features}")
                print(f"  - Intercept: 1")
            else:
                print(f"  - Coefficients: {n_features * n_classes}")
                print(f"  - Intercepts: {n_classes}")

    if f1Flag:
        if swapLabel:
            try:
                f1 = f1_score(y_test, y_pred,pos_label=0)
            except:
                f1 = f1_score(y_test, y_pred, pos_label='Plastic')
        else:
            f1 = f1_score(y_test, y_pred)
        results['f1_score'] = f1
    if cmFlag:
        if f1Flag:
            print(f'F1 Score of the Logistic Regression model: {f1}')
        else:
            print(f'Accuracy of the Logistic Regression model: {accuracy}')
        cm = confusion_matrix(y_test, y_pred)
        plt.figure(figsize=(8, 6))
        sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=le.classes_, yticklabels=le.classes_, annot_kws={"size": 16})
        plt.xlabel('Predicted', fontsize=16)
        plt.ylabel('Actual', fontsize=16)
        plt.xticks(fontsize=14)
        plt.yticks(fontsize=14)
        plt.title(f'LR Model Confusion Matrix for {str("-".join(y_orig.unique()))}', fontsize=18)
        if save_plot_name is not None:
            if f1Flag:
                plt.title(f'{save_plot_name.split("_")[1]} Confustion Matrix\nLR, n = {len(X_train)+len(X_test)}, F1 Score = {(f1 * 100.0):.1f}%', fontsize=18)
            else:
                plt.title(f'{save_plot_name.split("_")[1]} Confustion Matrix\nLR, n = {len(X_train)+len(X_test)}, Accuracy = {(accuracy* 100.0):.1f}%', fontsize=18)
            plt.savefig(save_plot_name, format='png', bbox_inches='tight')
            print(f"Saved PNG to {save_plot_name}")

            # Download the file
            files.download(save_plot_name)
        plt.show()
        results["CM"] = cm
        results["cm_labels"] = le.classes_
    if featureAnalysisFlag:
        model_coef = model.coef_[0]
        feature_names = X.columns
        feature_importance = pd.DataFrame({'Feature': feature_names, 'Importance': model_coef})
        feature_importance = feature_importance.sort_values(by='Importance', key=abs, ascending=False)
        top_n = int(len(feature_importance) * 0.201)
        top_features_df = feature_importance.head(top_n)
        top_features_df = top_features_df.reset_index(drop=True)
        if printFlag:
            print(f"Top 20% Features for LR:\n", top_features_df)
        results['feature_importance'] = top_features_df
    if recallFlag:
        recall = recall_score(y_test, y_pred, average= 'weighted',pos_label=1)
        print(f'Recall: {recall}')
        results['recall'] = recall
    if residualsFlag:
        misclassified = (y_pred != y_test).astype(int)
        misclassified_indices = np.where(misclassified)[0]
        #print(misclassified)
        mc_df = X_test.iloc[misclassified_indices]
        #print(mc_df)
        original_indices = X_test.iloc[misclassified_indices].index
        #print(original_indices)
        results['misclassified_indices'] = original_indices
        print("Coefficients:", model.coef_)
        # Use these indices to get the full rows from your original DataFrame
        #misclassified_original = df.loc[original_indices]
        #print(misclassified_original)
        ##OLD
        """
        y_prob = model.predict_proba(X_test)
        # Get the predicted class (the class with the highest predicted probability)
        y_pred_class = model.classes_[np.argmax(y_prob, axis=1)]
        # Calculate residuals as a binary indicator of misclassifications (1 for incorrect, 0 for correct)
        residuals = (y_pred_class != y_test).astype(int)
        # Plot residuals (misclassifications)
        plt.figure(figsize=(10, 6))
        plt.scatter(np.arange(len(y_test)), residuals, alpha=0.6)
        plt.axhline(y=0.5, color='r', linestyle='--')  # Reference line for misclassification
        plt.title('Residuals (Misclassifications) Plot for Logistic Regression')
        plt.xlabel('Test Sample Index')
        plt.ylabel('Misclassification (1=Incorrect, 0=Correct)')
        plt.tight_layout()
        plt.show()
        """
    return results
#-------------------------------------------------------------------------------
def RunSVM(group_name, df, printFlag=True, featureAnalysisFlag=False, residualsFlag=False, classificationReportFlag=False, randomState=42, cmFlag=False, kernelType = 'rbf', f1Flag = False, swapLabel=True, dataType='k', BICFlag=False, df_test=None, save_plot_name=None, recallFlag=False, chipSplit=False, chipGroup=0):
    results = {}
    X_train, X_test, y_train, y_test, X_train_scaled, X_test_scaled, X, y, y_orig, le = PrepXY(group_name, df, printFlag=printFlag, randomState=randomState, dataType=dataType, df_test=df_test, chipSplit=chipSplit,testChipGroup=chipGroup)
    if printFlag:
        print(X_train.columns[:20])
        print(f"Unique Y train values {np.unique(y_train, return_counts=True)}")
        print(f"Unique Y test values {np.unique(y_test, return_counts=True)}")
        print(f"Unique Y values {np.unique(y_orig, return_counts=True)}")

    # Use probability=True for BIC calculation if needed
    if BICFlag:
        svm_model = SVC(kernel=kernelType, random_state=42, probability=True)
    else:
        svm_model = SVC(kernel=kernelType, random_state=42)

    svm_model.fit(X_train_scaled, y_train)
    y_pred_svm = svm_model.predict(X_test_scaled)
    accuracy = accuracy_score(y_test, y_pred_svm)
    results['accuracy'] = accuracy
    #print(f'accuracy {accuracy}')

    if classificationReportFlag:
        print("Classification Report (SVM):\n", classification_report(y_test, y_pred_svm))
    if f1Flag:
        #print('in f1')
        if swapLabel:
            #print('in sl')
            if printFlag:
                print(f'y_test {y_test}')
                print(f'y_pred {y_pred_svm}')
            try:
                #print(f"in try")
                f1 = f1_score(y_test, y_pred_svm,pos_label=0)
                #print(f"in try f1 score {f1}")
            except:
                f1 = f1_score(y_test, y_pred_svm, pos_label='Plastic')
                #print(f'in except f1 score {f1}')
        else:
            f1 = f1_score(y_test, y_pred_svm, pos_label=1)
            #print(f"in else f1 score {f1}")
        results['f1_score'] = f1
    if cmFlag:
        if f1Flag:
            print(f'F1 Score of the SVM {kernelType} model: {f1}')
        else:
            print(f'Accuracy of the SVM {kernelType} model: {accuracy}')
        conf_matrix_svm = confusion_matrix(y_test, y_pred_svm)
        plt.figure(figsize=(8, 6))
        sns.heatmap(conf_matrix_svm, annot=True, fmt='d', cmap='Blues', xticklabels=le.classes_, yticklabels=le.classes_)
        plt.xlabel('Predicted')
        plt.ylabel('Actual')
        plt.title(f'SVM Model Confusion Matrix for {str("-".join(y_orig.unique()))}')
        if save_plot_name is not None:
            if group_name == 'Group_Full' and kernelType == 'linear':
                #classes = sorted(np.unique(y_test))
                label_dict = {'DI': 'Null', 'MC': 'PMMA', 'SC': 'PS', 'LC': 'LDPE', 'TC': 'PET', 'VC': 'PVC'}  # Adjust to your classes
                # Create label list from dict
                #classes = sorted(np.unique(y_test))
                print(le.classes_)
                labels = [label_dict[c] for c in le.classes_]

                # Plot
                plt.figure(figsize=(8, 6))
                sns.heatmap(conf_matrix_svm, annot=True, fmt='d', cmap='Blues',
                            xticklabels=labels,
                            yticklabels=labels, annot_kws={"size": 16})
                plt.xlabel('Predicted', fontsize=16)
                plt.ylabel('Actual', fontsize=16)
                plt.xticks(fontsize=14)
                plt.yticks(fontsize=14)
                plt.title(f'SVM Model Confusion Matrix')
            if kernelType == 'linear':
                title_str = f'{save_plot_name.split("_")[1]} Confustion Matrix\nSVM_L, n = {len(X_train)+len(X_test)}'
            else:
                title_str = f'{save_plot_name.split("_")[1]} Confustion Matrix\nSVM_R, n = {len(X_train)+len(X_test)}'
            if f1Flag:
                title_str += f', F1 Score = {(f1* 100.0):.1f}%'
            else:
                title_str += f', Accuracy = {(accuracy* 100.0):.1f}%'
            plt.title(title_str, fontsize=18)
            plt.savefig(save_plot_name, format='png', bbox_inches='tight')
            print(f"Saved PNG to {save_plot_name}")
            plt.show()
            # Download the file
            files.download(save_plot_name)
        plt.show()
        results["CM"] = conf_matrix_svm
        results["cm_labels"] = le.classes_
    if featureAnalysisFlag and kernelType == 'linear':
        feature_importance = np.max(np.abs(svm_model.coef_), axis=0)  # Takes the max coef value of the feature across all classes
        feature_names = X_train.columns
        # Create a DataFrame with feature names and their importances
        importance_df = pd.DataFrame({
            'Feature': feature_names,
            'Importance': feature_importance
        })
        # Sort by importance
        importance_df = importance_df.sort_values(by='Importance', ascending=False)
        # Get the top 20%
        top_n = int(len(importance_df) * 0.201)
        top_features_df = importance_df.head(top_n)
        top_features_df = top_features_df.reset_index(drop=True)
        if printFlag:
            print("Top 20% Important Features for SVM:\n", top_features_df)
        results['feature_importance'] = top_features_df
    if recallFlag:
        recall = recall_score(y_test, y_pred_svm, average='weighted')
        print(f'Recall: {recall}')
        results['recall'] = recall
    if BICFlag:
        # Calculate BIC for SVM
        # Get predicted probabilities on test set
        y_pred_proba = svm_model.predict_proba(X_test_scaled)

        # Calculate log-likelihood
        # For each sample, get the probability of the true class
        log_likelihood = 0
        for i, true_class in enumerate(y_test):
            # Find the index of the true class in the classes array
            class_idx = np.where(svm_model.classes_ == true_class)[0][0]
            # Add log probability of the true class (avoid log(0))
            prob = max(y_pred_proba[i, class_idx], 1e-15)
            log_likelihood += np.log(prob)

        # Calculate number of parameters
        n_samples = len(X_train_scaled)
        n_features = X_train_scaled.shape[1]
        n_classes = len(svm_model.classes_)

        # For SVM, parameter count approximation:
        # - Support vectors contribute to model complexity
        # - For non-linear kernels, effective parameters depend on support vectors
        if kernelType == 'linear':
            # Linear SVM: n_features * (n_classes - 1) + (n_classes - 1) bias terms
            n_params = n_features * (n_classes - 1) + (n_classes - 1)
        else:
            # Non-linear SVM: approximate using number of support vectors
            n_support_vectors = len(svm_model.support_)
            n_params = n_support_vectors

        # Calculate BIC = -2 * log_likelihood + n_params * log(n_samples)
        bic = -2 * log_likelihood + n_params * np.log(len(y_test))

        results['bic'] = bic
        results['log_likelihood'] = log_likelihood
        results['n_params'] = n_params

        if printFlag:
            print(f"BIC: {bic:.4f}")
            print(f"Log-likelihood: {log_likelihood:.4f}")
            print(f"Number of parameters: {n_params}")
            if kernelType != 'linear':
                print(f"Number of support vectors: {len(svm_model.support_)}")
    if residualsFlag:
        misclassified = (y_pred_svm != y_test).astype(int)
        misclassified_indices = np.where(misclassified)[0]
        #print(misclassified)
        mc_df = X_test.iloc[misclassified_indices]
        #print(mc_df)
        feature_names = X_test.columns.tolist()
        if kernelType == 'linear':
            #print("Coefficients:", svm_model.coef_)
            feature_importance = np.abs(svm_model.coef_).mean(axis=0)
            # Get ranked indices (highest to lowest)
            ranked_features = np.argsort(feature_importance)[::-1]

            print("Feature Rankings (by mean absolute coefficient):")
            for rank, feature_idx in enumerate(ranked_features, 1):
                print(f"{rank}. Feature {feature_idx}: {feature_importance[feature_idx]:.4f}")
            importance_df = pd.DataFrame({
                'Feature': feature_names,
                'Importance': feature_importance
            }).sort_values('Importance', ascending=False).reset_index(drop=True)

            importance_df['Rank'] = range(1, len(importance_df) + 1)
            for idx, row in importance_df.iterrows():
                print(f"{row['Rank']:2.0f}. {row['Feature']:20s}: {row['Importance']:.4f}")
        """else:
            print('past the else')
            model = SVC(kernel=kernelType, probability=True, random_state=42)
            model.fit(X_train, y_train)
            print('fit the model')
            explainer = shap.KernelExplainer(
                model.predict_proba,
                shap.sample(X_train)  # use sample for speed
            )
            print('explainer made')
            # Calculate SHAP values (on a sample if dataset is large)
            shap_values = explainer.shap_values(X_test)
            print(f"Type of shap_values: {type(shap_values)}")
            print(f"Length of shap_values (number of classes): {len(shap_values)}")
            print(f"Shape of first class: {shap_values[0].shape}")
            print(f"Shape after np.array: {np.array(shap_values).shape}")
            shap.summary_plot(shap_values, X_test, feature_names=feature_names)

            # Get mean absolute SHAP values across all samples and classes
            mean_shap = np.abs(shap_values).mean(axis=0).mean(axis=0)
            print('shap values calculated')
            print(feature_names)
            print(mean_shap)
            avg_importance = np.abs(np.array(shap_values)).mean(axis=1).mean(axis=0)
            print(avg_importance)
            feature_importance_df = pd.DataFrame({
                'feature': feature_names,
                'avg_importance': avg_importance
            }).sort_values('avg_importance', ascending=False)

            print(feature_importance_df)

            #print(feature_importance)
            """
        original_indices = X_test.iloc[misclassified_indices].index
        #print(original_indices)
        results['misclassified_indices'] = original_indices
    return results
#-------------------------------------------------------------------------------
def RunLDA(group_name, df, printFlag=False, featureAnalysisFlag=False, residualsFlag=False, classificationReportFlag=False, randomState=42, cmFlag=False, f1Flag = False, swapLabel=True, dataType='Slope', BICFlag=False, kernelType=None, df_test=None, save_plot_name=None, recallFlag=False, chipSplit=False, chipGroup=0):
    #print("inside RunLDA")
    results = {}
    X_train, X_test, y_train, y_test, X_train_scaled, X_test_scaled, X, y, y_orig, le = PrepXY(group_name, df, printFlag=printFlag, randomState=randomState, dataType=dataType, df_test=df_test, chipSplit=chipSplit,testChipGroup=chipGroup)
    if printFlag:
        print(X_train.columns[:20])
    lda = LinearDiscriminantAnalysis()
    lda.fit(X_train_scaled, y_train)
    y_pred = lda.predict(X_test_scaled)
    if classificationReportFlag:
        print("Classification Report (LDA):\n", classification_report(y_test, y_pred))
    accuracy = accuracy_score(y_test, y_pred)
    results['accuracy'] = accuracy

    # Calculate BIC if requested
    if BICFlag:
        # Get predicted probabilities for log-likelihood calculation
        y_pred_proba = lda.predict_proba(X_test_scaled)

        # Calculate log-likelihood
        log_likelihood = 0
        for i, true_label in enumerate(y_test):
            log_likelihood += np.log(y_pred_proba[i, true_label])

        # Calculate number of parameters for LDA
        # For LDA: n_features * (n_classes - 1) for discriminant coefficients
        # + n_classes for class priors + n_features for means per class
        # + covariance matrix parameters (n_features * (n_features + 1) / 2)
        n_features = X_train_scaled.shape[1]
        n_classes = len(lda.classes_)

        # Parameters: discriminant coefficients + class priors + class means + shared covariance matrix
        n_params = (n_features * (n_classes - 1) +  # discriminant coefficients
                   (n_classes - 1) +  # class priors (one less due to constraint)
                   n_features * n_classes +  # class means
                   n_features * (n_features + 1) // 2)  # shared covariance matrix

        n_samples = len(y_test)

        # Calculate BIC: -2 * log_likelihood + k * log(n)
        bic = -2 * log_likelihood + n_params * np.log(n_samples)
        results['bic'] = bic

        if printFlag:
            print(f"BIC of the LDA model: {bic}")
            print(f"Number of parameters: {n_params}")
            print(f"  - Discriminant coefficients: {n_features * (n_classes - 1)}")
            print(f"  - Class priors: {n_classes - 1}")
            print(f"  - Class means: {n_features * n_classes}")
            print(f"  - Covariance matrix: {n_features * (n_features + 1) // 2}")
    if f1Flag:
        #print('in f1')
        if swapLabel:
            #print('in sl')
            try:
                #print('in try')
                f1 = f1_score(y_test, y_pred,pos_label=0)
            except:
                f1 = f1_score(y_test, y_pred, pos_label='Plastic')
        else:
            f1 = f1_score(y_test, y_pred)
        results['f1_score'] = f1
    if cmFlag:
        if f1Flag:
            print(f'F1 Score of the LDA model: {f1}')
        else:
            print(f'Accuracy of the LDA model: {accuracy}')
        cm = confusion_matrix(y_test, y_pred)
        plt.figure(figsize=(8, 6))
        sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=le.classes_, yticklabels=le.classes_)
        plt.xlabel('Predicted')
        plt.ylabel('Actual')
        plt.title(f'LDA Model Confusion Matrix for {str("-".join(y_orig.unique()))}')
        if save_plot_name is not None:
            if f1Flag:
                plt.title(f'{save_plot_name.split("_")[1]} Confustion Matrix\nLDA, n = {len(X_train)+len(X_test)}, F1 Score = {(f1 * 100.0):.1f}%')
            else:
                plt.title(f'{save_plot_name.split("_")[1]} Confustion Matrix\nLDA, n = {len(X_train)+len(X_test)}, Accuracy = {(accuracy* 100.0):.1f}%')
            plt.savefig(save_plot_name, format='png', bbox_inches='tight')
            print(f"Saved PNG to {save_plot_name}")

            # Download the file
            files.download(save_plot_name)
        plt.show()
        results["CM"] = cm
        results["cm_labels"] = le.classes_
    if recallFlag:
        recall = recall_score(y_test, y_pred, average='weighted')
        print(f'Recall: {recall}')
        results['recall'] = recall
    if featureAnalysisFlag:
        feature_importance = np.max(np.abs(lda.coef_), axis=0)  # Takes the max coef value of the feature across all classes
        feature_names = X_train.columns
        importance_df = pd.DataFrame({
            'Feature': feature_names,
            'Importance': feature_importance
        })
        importance_df = importance_df.sort_values(by='Importance', ascending=False)
        top_n = int(len(importance_df) * 0.201)
        top_features_df = importance_df.head(top_n)
        top_features_df = top_features_df.reset_index(drop=True)
        if printFlag:
            print("Top 20% Important Features for LDA:\n", top_features_df)
        results['feature_importance'] = top_features_df
    return results
#-------------------------------------------------------------------------------
def RunLRL1(group_name, df, printFlag=False, featureAnalysisFlag=False, residualsFlag=False, classificationReportFlag=False, randomState=42, cvFold=5, solver='saga', cmFlag=False, f1Flag = False, swapLabel=True, dataType='Slope', BICFlag=False, kernelType=None, df_test=None):
    results = {}
    X_train, X_test, y_train, y_test, X_train_scaled, X_test_scaled, X, y, y_orig, le, X_val_scaled, X_val, y_val = PrepXY(group_name, df, printFlag=printFlag, randomState=randomState, valFlag=True, dataType=dataType, df_test=df_test)
    warnings.filterwarnings("ignore", category=ConvergenceWarning)
    log_reg_cv = LogisticRegressionCV(cv=cvFold, penalty='l1', solver=solver, max_iter=1000, class_weight='balanced')  # CV to find alpha
    log_reg_cv.fit(X_val_scaled, y_val)
    #warnings.filterwarnings("default", category=ConvergenceWarning) #Reset to default behavior

    ##### LR L1 w/ best alpha from CV #####
    lasso_logistic_best_alpha = LogisticRegression(penalty='l1', solver='saga', C=log_reg_cv.C_[0], max_iter=1000, class_weight='balanced')
    lasso_logistic_best_alpha.fit(X_train_scaled, y_train)

    y_pred = lasso_logistic_best_alpha.predict(X_test_scaled)
    accuracy = accuracy_score(y_test, y_pred)
    results['accuracy'] = accuracy
    if classificationReportFlag:
        print("Classification Report (LR L1):\n", classification_report(y_test, y_pred))
    if printFlag:
        print(f"Accuracy of the LR L1 model: {accuracy}")

    # Calculate BIC if requested
    if BICFlag:
        # Get predicted probabilities for log-likelihood calculation
        y_pred_proba = lasso_logistic_best_alpha.predict_proba(X_test_scaled)

        # Calculate log-likelihood
        log_likelihood = 0
        for i, true_label in enumerate(y_test):
            log_likelihood += np.log(y_pred_proba[i, true_label])

        # Count non-zero coefficients (effective parameters)
        n_params = np.sum(lasso_logistic_best_alpha.coef_ != 0) + 1  # +1 for intercept
        n_samples = len(y_test)

        # Calculate BIC: -2 * log_likelihood + k * log(n)
        bic = -2 * log_likelihood + n_params * np.log(n_samples)
        results['bic'] = bic

        if printFlag:
            print(f"BIC of the LR L1 model: {bic}")
            print(f"Number of non-zero parameters: {n_params}")
    if f1Flag:
        if swapLabel:
            try:
                f1 = f1_score(y_test, y_pred,pos_label=0)
            except:
                f1 = f1_score(y_test, y_pred, pos_label='Plastic')
        else:
            f1 = f1_score(y_test, y_pred)
        results['f1_score'] = f1
    # Generate and plot the confusion matrix
    if cmFlag:
        if f1Flag:
            print(f'F1 Score of the LRL1 model: {f1}')
        else:
            print(f'Accuracy of the LRL1 model: {accuracy}')
        cm = confusion_matrix(y_test, y_pred)
        plt.figure(figsize=(8, 6))
        sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=le.classes_, yticklabels=le.classes_)
        plt.xlabel('Predicted')
        plt.ylabel('Actual')
        plt.title(f'Logistic Regression (L1) Model Confusion Matrix for {str("-".join(y_orig.unique()))}')
        plt.show()

    if featureAnalysisFlag:
        model_coef = lasso_logistic_best_alpha.coef_[0]
        feature_names = X.columns
        feature_importance = pd.DataFrame({'Feature': feature_names, 'Importance': model_coef})
        feature_importance = feature_importance.sort_values(by='Importance', key=abs, ascending=False)

        # Get top 20% of features
        top_n = int(len(feature_importance) * 0.201)
        top_features_df = feature_importance.head(top_n)
        top_features_df = top_features_df.reset_index(drop=True)
        if printFlag:
            print(f"Top 20% Features for LRL1:\n", top_features_df)
        results['feature_importance'] = top_features_df
    return results
#-------------------------------------------------------------------------------
def RunkNN(group_name, df, k=5, printFlag=False, featureAnalysisFlag=False, residualsFlag=False, classificationReportFlag=False, randomState=42, cmFlag=False, f1Flag = False, swapLabel=False, dataType='Slope', BICFlag=False, kernelType=None):
    results = {}
    X_train, X_test, y_train, y_test, X_train_scaled, X_test_scaled, X, y, y_orig, le, X_val_scaled, X_val, y_val = PrepXY(group_name, df, printFlag=printFlag, randomState=randomState, valFlag=True, dataType=dataType)
    knn_initial = KNeighborsClassifier(n_neighbors=k)
    param_grid = {'n_neighbors': list(range(1, 21))}  # Try k from 1 to 20

    # Set up the grid search with 5-fold cross-validation
    grid_search = GridSearchCV(knn_initial, param_grid, cv=5, scoring='accuracy')

    # Run the grid search on the training data
    grid_search.fit(X_val, y_val)
    k_best = grid_search.best_params_['n_neighbors']
    if printFlag:
        print(f"Best k: {k_best}")
    knn = KNeighborsClassifier(n_neighbors=k_best)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    results['accuracy'] = accuracy
    if classificationReportFlag:
        print("Classification Report (kNN):\n", classification_report(y_test, y_pred))
    if printFlag:
        print(f"Accuracy of the kNN model: {accuracy}")
    if cmFlag:
        print(f'Accuracy of the kNN model: {accuracy}')
        cm = confusion_matrix(y_test, y_pred)
        plt.figure(figsize=(8, 6))
        sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=le.classes_, yticklabels=le.classes_)
        plt.xlabel('Predicted')
        plt.ylabel('Actual')
        plt.title(f'kNN (K = {k_best}) Model Confusion Matrix for {str("-".join(y_orig.unique()))}')
        plt.show()
    if f1Flag:
        if swapLabel:
            try:
                f1 = f1_score(y_test, y_pred,pos_label=0)
            except:
                f1 = f1_score(y_test, y_pred, pos_label='Plastic')
        else:
            f1 = f1_score(y_test, y_pred)
        results['f1_score'] = f1
    return results
#-------------------------------------------------------------------------------
def RunkMeans(group_name, df, k=2, printFlag=False, featureAnalysisFlag=False, residualsFlag=False, classificationReportFlag=False, randomState=42, cmFlag=False, f1Flag = False, swapLabel=False):
    """(5/6/2025) Doesn't work well; ARI is negative..."""
    results = {}
    X = df[data.columns[2:-7]] #Remove all labels from the feature dataframe
    #y = df[group_name] #identify y as the label column
    # Step 3: Normalize the data
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    kmeans = KMeans(n_clusters=k, random_state=42)
    clusters = kmeans.fit_predict(X_scaled)
    #df['Cluster'] = clusters
    labels = LabelEncoder().fit_transform(df['Group_PN'])
    ari = adjusted_rand_score(labels, clusters)
    print(f"Adjusted Rand Index (ARI): {ari:.2f}")
    inertias = []
    for k in range(1, 15):
        km = KMeans(n_clusters=k, random_state=42)
        km.fit(X_scaled)
        inertias.append(km.inertia_)

    plt.plot(range(1, 15), inertias, marker='o')
    plt.xlabel('Number of Clusters')
    plt.ylabel('Inertia')
    plt.title('Elbow Method for Optimal k')
    plt.grid(True)
    plt.show()
#-------------------------------------------------------------------------------
def RunXGBoost(group_name, df, printFlag=False, featureAnalysisFlag=False, residualsFlag=False, classificationReportFlag=False, randomState=42, cmFlag=False, FinalFlag=False, accuraciesFlag=False, f1Flag=False, swapLabel=False, dataType='Slope', BICFlag=False, kernelType=None, df_test=None):
    results = {}
    X_train, X_test, y_train, y_test, X_train_scaled, X_test_scaled, X, y, y_orig, le = PrepXY(group_name, df, printFlag=printFlag, randomState=randomState, dataType=dataType, df_test=df_test)
    if group_name == 'Group_PN' and df_test is not None:
        y_train = y_train.apply(lambda x: 0 if x=='Null' else 1)
        y_test = y_test.apply(lambda x: 0 if x=='Null' else 1)
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)
    params = {
        'objective': 'multi:softmax',  # Multi-class classification
        'num_class': len(np.unique(y)),  # Number of classes
        'eval_metric': ['merror', 'mlogloss'],  # Evaluation metric, merror for misclassification error
    }
    watchlist = [(dtrain, 'train'), (dtest, 'eval')]
    num_boost_round = 100
    evals_result = {}
    #model = xgb.train(params, dtrain, num_boost_round=num_boost_round, evals=watchlist, early_stopping_rounds=10, evals_result=evals_result, verbose_eval=False)
    model = xgb.train(params, dtrain, num_boost_round=num_boost_round, evals=watchlist, evals_result=evals_result, verbose_eval=False)

    # Get predictions from the trained model
    y_pred = model.predict(dtest)
    val_accuracy = accuracy_score(y_test, y_pred)

    eval_loss = evals_result["eval"]["mlogloss"]
    train_loss = evals_result["train"]["mlogloss"]
    eval_merror = evals_result["eval"]["merror"]
    train_merror = evals_result["train"]["merror"]
    train_accuracy = [1 - merror for merror in train_merror]
    eval_accuracy = [1 - merror for merror in eval_merror]


    if FinalFlag: #showing raw final results (maybe not best)
    # Print confusion matrix
        cm = confusion_matrix(y_test, y_pred)
        plt.figure(figsize=(8, 6))
        sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=le.classes_, yticklabels=le.classes_)
        plt.xlabel('Predicted')
        plt.ylabel('Actual')
        plt.title(f'Final Model Confusion Matrix {str("-".join(y.unique()))}')
        plt.show()

        # Print the final tree (e.g., the 99th tree if num_boost_round=100)
        xgb.plot_tree(model, num_trees=num_boost_round - 1)
        plt.show()

    ############ BEST MODEL ############
    best_iteration = np.argmax(eval_accuracy)  # Find the index of the highest validation accuracy
    # Get the best model at that iteration
    evals_result = {}
    best_tree_dump = model.get_dump()[best_iteration]
    if printFlag:
        print(f"Final Validation Accuracy: {val_accuracy:.4f}")
        print(f"Final Training Loss: {train_loss[-1]}")
        print(f"Final Validation Loss: {eval_loss[-1]}")
        print(f"Final Training Misclassification Error: {train_merror[-1]}")
        print(f"Final Validation Misclassification Error: {eval_merror[-1]}")
        print(f"Final Training Accuracy: {train_accuracy[-1]}")
        print(f"Final Validation Accuracy: {eval_accuracy[-1]}")
        print(f"Best iteration (with highest validation accuracy): {best_iteration}")
        print(f"\033[1mBest Validation Accuracy: {eval_accuracy[best_iteration]:.4f}\033[0m")
    #model_best = xgb.train(params, dtrain, num_boost_round=best_iteration+1, evals=watchlist, early_stopping_rounds=10, evals_result=evals_result, verbose_eval=False)
    model_best = xgb.train(params, dtrain, num_boost_round=best_iteration+1, evals=watchlist, evals_result=evals_result, verbose_eval=False)
    y_pred_best = model_best.predict(dtest)
    val_accuracy_best = accuracy_score(y_test, y_pred_best)
    results['accuracy'] = val_accuracy_best
    if printFlag:
        print(val_accuracy_best)

    y_test_original = le.inverse_transform(y_test)
    #print(y_pred_best)
    y_pred_original = le.inverse_transform(y_pred_best.astype(int))
    #y_pred_original = le.inverse_transform(y_pred_encoded)

    # Calculate BIC if requested
    if BICFlag:
        # Get predictions with probabilities for log-likelihood calculation
        params_prob = params.copy()
        params_prob['objective'] = 'multi:softprob'
        model_prob = xgb.train(params_prob, dtrain, num_boost_round=best_iteration+1, verbose_eval=False)
        y_pred_proba = model_prob.predict(dtest)

        # Calculate log-likelihood
        n_samples = len(y_test)
        n_classes = len(np.unique(y))

        # Reshape probabilities if needed
        if len(y_pred_proba.shape) == 1:
            y_pred_proba = y_pred_proba.reshape(-1, n_classes)

        # Calculate log-likelihood
        log_likelihood = 0
        for i in range(n_samples):
            true_class = int(y_test[i])
            predicted_prob = y_pred_proba[i, true_class]
            # Add small epsilon to avoid log(0)
            predicted_prob = max(predicted_prob, 1e-15)
            log_likelihood += np.log(predicted_prob)

        # Calculate number of parameters
        # For XGBoost: roughly (num_trees * max_depth * num_features * num_classes)
        # This is an approximation as the actual parameter count depends on tree structure
        num_trees = best_iteration + 1
        max_depth = params.get('max_depth', 6)  # default XGBoost max_depth
        num_features = X_train.shape[1]
        # Approximate number of parameters (this is a rough estimate)
        k = num_trees * max_depth * num_features

        # Calculate BIC: BIC = -2 * log_likelihood + k * log(n)
        bic = -2 * log_likelihood + k * np.log(n_samples)

        results['bic'] = bic
        results['log_likelihood'] = log_likelihood
        results['num_parameters'] = k

        if printFlag:
            print(f"Log-likelihood: {log_likelihood:.4f}")
            print(f"Number of parameters (estimated): {k}")
            print(f"BIC: {bic:.4f}")

    if classificationReportFlag:
        print("Classification Report (XGBoost):\n", classification_report(y_test, y_pred))
    if f1Flag:
        if swapLabel:
            try:
                f1 = f1_score(y_test, y_pred,pos_label=0)
            except:
                f1 = f1_score(y_test, y_pred, pos_label='Plastic')
        else:
            f1 = f1_score(y_test, y_pred)
        results['f1_score'] = f1
    # Print confusion matrix
    if cmFlag:
        if f1Flag:
            print(f'F1 Score of the XGBoost model: {f1}')
        else:
            print(f'Accuracy of the XGBoost model: {val_accuracy_best}')
        cm = confusion_matrix(y_test, y_pred)
        plt.figure(figsize=(8, 6))
        sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=le.classes_, yticklabels=le.classes_)
        plt.xlabel('Predicted')
        plt.ylabel('Actual')
        plt.title(f'XGBoost Model Confusion Matrix for {str("-".join(y_orig.unique()))}')
        plt.show()

    # Plot accuracies vs boosting round
    if accuraciesFlag:
        plt.figure(figsize=(12, 6))
        plt.subplot(1, 2, 1)
        plt.plot(range(len(train_accuracy)), train_accuracy, label='Training Accuracy')
        plt.plot(range(len(eval_accuracy)), eval_accuracy, label='Validation Accuracy')
        plt.xlabel('Boosting Round')
        plt.ylabel('Accuracy')
        plt.title('Training and Validation Accuracy over Boosting Rounds')
        plt.legend()
    if featureAnalysisFlag:
        feature_importance = model_best.get_score(importance_type='gain')
        feature_importance_df = pd.DataFrame(list(feature_importance.items()), columns=['Feature', 'Importance'])
        feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)
        top_n = int(len(feature_importance_df) * 0.201)
        top_features_df = feature_importance_df.head(top_n)
        top_features_df = top_features_df.reset_index(drop=True)
        if printFlag:
            print("Top 20% Important Features for XGBoost:\n", top_features_df)
        results['feature_importance'] = top_features_df
    return results
#-------------------------------------------------------------------------------
def PlotAvgIndex(group_name, df, metric, num_rows, formatted_counts, saveFlag=False):
    """Expects to be plotting scatter plots of metric values for ML algorithms across
    the index of random data splits"""
    if metric not in ["F1", "Accuracy"]:
        raise ValueError("Invalid metric. Please use 'F1' or 'Accuracy'.")
    models = {
        'SVM': {'color': 'b'},
        'LDA': {'color': 'g'},
        'LR': {'color': 'r'},
        'XGB': {'color': 'orange'},
        'LRL1': {'color': 'purple'},
        'kNN': {'color': 'black'}
    }
    plt.figure(figsize=(10, 6))
    for model, props in models.items():
        col = f'{model}_{metric}'
        avg = df[col].mean()
        plt.plot(df['random_state'].astype(str), df[col], label=f'{model} {metric}', marker='o', linestyle='-', color=props['color'])
        plt.axhline(y=avg, color=props['color'], linestyle='--', label=f'Avg {model} {metric}: {avg:.2f}')

    # Final touches
    plt.xlabel('Random State (Index)')
    plt.ylabel(metric)
    #plt.title(f'Model {metric} Scores Over Random State Index for {group_name} \n {num_rows} Total Data Objects, {formatted_counts}')
    plt.title(f'Model {metric} Scores Over Random State Index for {group_name}')
    # Second line, smaller font, just below the main title
    plt.suptitle(f'{num_rows} Total Data Objects, {formatted_counts}', fontsize=10, y=0.94)
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True)
    plt.show()
    if saveFlag:
        plt.savefig(f"model_{metric}_scores.png", dpi=300)
#-------------------------------------------------------------------------------
def fi_df_to_results_dict(fi_df):
    results = {}
    model_columns = [col for col in fi_df.columns if "Feature_Importance" in col]

    for model in model_columns:
        dfs = []
        for idx, entry in fi_df[model].items():
            if isinstance(entry, pd.DataFrame):
                df = entry.copy()
                df["Rank"] = df.index + 1  # Preserve original fi_df index
                dfs.append(df)

        if dfs:
            combined_df = pd.concat(dfs, ignore_index=True)
            results[model] = combined_df
        else:
            print(f"Warning: No valid DataFrames for {model}")
            results[model] = pd.DataFrame()  # Or skip if preferred

    return results
#-------------------------------------------------------------------------------
def FeatureAnalysis(fi_df, num_rows, formatted_counts, groupName, addedName, saveFlag=False, printFlag=False, rankLimit=None, dataType='Slope'):
    from datetime import datetime
    from pathlib import Path
    today_str = datetime.today().strftime('%Y%m%d')
    drive_path = Path('/content/drive/MyDrive/Lexi/MNP/ML Analysis/FeatureAnalysisPlots')
    r_iter = fi_df.shape[0]
    subtitle = f'{num_rows} Total Data Objects, {formatted_counts}, {r_iter} iterations'
    results = fi_df_to_results_dict(fi_df)
    processed_dfs = []
    for key in ['SVM_Feature_Importance', 'LDA_Feature_Importance', 'XGB_Feature_Importance','LR_Feature_Importance', 'LRL1_Feature_Importance']:
        if not results[key].empty:
            df = results[key].copy()
            #df['Rank'] = df.index + 1
            df['Model'] = key.split('_')[0]  # Extract model name
            if dataType == 'Slope':
                df[['Time', 'Reagent']] = df['Feature'].str.split('_', expand=True)
            elif dataType == 'k':
                df['Time'] = np.nan
                df['Reagent'] = df['Feature']
            df['Reagent_Type'] = df["Reagent"].str[0]
            df['Reagent_Conc'] = df["Reagent"].str[1]
            #df = df[['Model', 'Reagent', 'Time', 'Importance', 'Rank']]
            processed_dfs.append(df)
    # Combine all
    combined_df = pd.concat(processed_dfs, axis=0, ignore_index=True)
    if rankLimit is not None:
        combined_df = combined_df[combined_df['Rank'] <= rankLimit]
    if printFlag:
        print(results)
        print(combined_df)

    r_counts_df = combined_df['Reagent'].value_counts()
    r_counts = ' '.join(f'{group}:{count}' for group, count in r_counts_df.items())
    print(r_counts)
    t_counts_df = combined_df['Time'].value_counts()
    t_counts = ' '.join(f'{group}:{count}' for group, count in t_counts_df.items())
    print(t_counts)
    f_counts_df = combined_df['Feature'].value_counts()
    f_counts = ' '.join(f'{group}:{count}' for group, count in f_counts_df.items())
    print(f_counts)
    if dataType == 'Slope':
        plt.figure(figsize=(8, 4))
        r_counts_df.plot(kind='bar', color='skyblue')
        #plt.title('Feature Counts by Reagent')
        #plt.suptitle(f'{num_rows} Total Data Objects, {formatted_counts}', fontsize=10, y=0.94)
        plt.suptitle(f'Feature Counts by Reagent\n{subtitle}', fontsize=14, y=0.95)

        plt.xlabel('Reagent')
        plt.ylabel('Count')
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()
        plt.figure(figsize=(8, 4))
        t_counts_df.plot(kind='bar', color='salmon')
        plt.suptitle(f'Feature Counts by Time\n{subtitle}', fontsize=14, y=0.95)
        plt.xlabel('Time')
        plt.ylabel('Count')
        plt.xticks(rotation=45)
        plt.tight_layout()
        if saveFlag:
            file_path = drive_path / f"{today_str}_{groupName}_FA_Times_{addedName}.png"
            plt.savefig(file_path, dpi=300)
        plt.show()
    plt.figure(figsize=(8, 4))
    f_counts_df.plot(kind='bar', color='lightgreen')
    #plt.title('Feature Counts by Feature')
    #plt.suptitle(f'{num_rows} Total Data Objects, {formatted_counts}', fontsize=10, y=0.94)
    plt.suptitle(f'Feature Counts by Feature\n{subtitle}', fontsize=14, y=0.95)

    plt.xlabel('Feature')
    plt.ylabel('Count')
    plt.xticks(rotation=90, fontsize=4)
    plt.tight_layout()
    plt.show()
    print(f_counts_df)

    # Count occurrences of each (Reagent_Type, Sub_Reagent) pair
    #reagent_counts = combined_df.groupby(['Reagent_Type', 'Reagent_Conc']).size().unstack(fill_value=0)
    reagent_counts = combined_df.groupby(['Reagent_Type', 'Reagent_Conc']).size().unstack(fill_value=0)

    # Sort by total count (row sum) to order by y-axis value
    reagent_counts = reagent_counts.loc[reagent_counts.sum(axis=1).sort_values(ascending=False).index]

    # Plot
    reagent_counts.plot(kind='bar', stacked=True, figsize=(8, 6), color=['lightblue', 'lightgreen'])

    #plt.title('Reagent Counts by Type')
    #plt.suptitle(f'{num_rows} Total Data Objects, {formatted_counts}', fontsize=10, y=0.94)
    plt.suptitle(f'Reagent Counts by Type\n{subtitle}', fontsize=14, y=0.95)

    plt.xlabel('Reagent Type')
    plt.ylabel('Count')
    plt.xticks(rotation=0)
    plt.legend(title='Conc', bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()
    if saveFlag:
        file_path = drive_path / f"{today_str}_{groupName}_FA_ReagentsConc_{addedName}.png"
        plt.savefig(file_path, dpi=300)
    plt.show()
    if dataType=='Slope':
        # Barplot for Time
        combined_df['Time'] = pd.to_numeric(combined_df['Time'], errors='coerce')

        # Define bins and labels
        bins = [15, 100, 200, 300, 400, 500, 600, 700, 800]
        labels = ['15–100', '100–200', '200–300', '300–400', '400-500', '500-600', '600-700', '700-800']

        # Bin the Time values
        combined_df['Time_Bin'] = pd.cut(combined_df['Time'], bins=bins, labels=labels, right=False)
        time_bin_counts = combined_df['Time_Bin'].value_counts().sort_index()

        # Plot
        plt.figure(figsize=(8, 4))
        time_bin_counts.plot(kind='bar', color='darkorange')
        #plt.title('Feature Counts by Time Bin')
        plt.suptitle(f'Feature Counts by Time Bin\n{subtitle}', fontsize=14, y=0.95)
        plt.xlabel('Time Range (frames)')
        plt.ylabel('Count')
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()

    reagent_counts = combined_df.groupby(['Model', 'Reagent_Type']).size().unstack(fill_value=0)
    print(reagent_counts)

    # Plot
    reagent_counts.plot(kind='bar', stacked=True, figsize=(10, 6), colormap='tab20')

    #plt.title('Top Feature Reagent Counts per Model')
    #plt.suptitle(f'{num_rows} Total Data Objects, {formatted_counts}', fontsize=10, y=0.98)
    plt.suptitle(f'Top Feature Reagent Counts per Model\n{subtitle}', fontsize=14, y=0.95)
    plt.xlabel('Model')
    plt.ylabel('Number of Top Features')
    plt.xticks(rotation=0)
    plt.legend(title='Reagent', bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()
    if saveFlag:
        file_path = drive_path / f"{today_str}_{groupName}_FA_ReagentsPerModel_{addedName}.png"
        plt.savefig(file_path, dpi=300)
    plt.show()
#-------------------------------------------------------------------------------
def WrangleKData(filePath, printFlag=False, kdiffFlag=True, selectedPlasticsList=['MCH', 'MCM', 'MCL', "MSH", "MSM", "MSL", "SCH", "SCM", "SCL", "SSH", "SSM", "SSL", "LCH", "LCM", "LCL", "VCH", "VCM", "VCL", "4", "3", "2", "1", "TCH", "TCM", "TCL", "15", "16", "17", "18", "BCH", "BCM", "BCL", "25", "26", "27", "28", "CCH", "CCM", "CCL"],
                selectedNotPlasticsList = [], selectedReagentsList=[], selectedNotReagentsList=[]):
    """ To organize a suitable dataframe for k data for use with ML """
    df = pd.read_csv(filePath, index_col=0)
    df.reset_index(0, inplace=True)
    df["Plastic"] = df["Plastic"].astype(str)
    if printFlag:
        print(f'Input File Path: {filePath}')
        print(f'Selected Plastics to include: {selectedPlasticsList}')
        print(f'Selected Plastics to exclude: {selectedNotPlasticsList}')
        print(f'Selected Reagents to include: {selectedReagentsList}')
        print(f'Selected Reagents to exclude: {selectedNotReagentsList}')
        #dataFrame.head()
    if len(selectedReagentsList) > 0:
        df = df[df['Reagent'].isin(selectedReagentsList)]
    if len(selectedNotReagentsList) > 0:
        df = df[~df['Reagent'].isin(selectedNotReagentsList)]
    if len(selectedPlasticsList) > 0:
        df = df[df['Plastic'].isin(selectedPlasticsList)]
    if len(selectedNotPlasticsList) > 0:
        df = df[~df['Plastic'].isin(selectedNotPlasticsList)]
    if printFlag:
        print(f'Unique Plastics: {df["Plastic"].unique()}')
        # Before the pivot, check if you have complete data
        print("Unique combinations in your filtered data:")
        print(f"Plastics: {len(df['Plastic'].unique())}")
        print(f"Channels: {len(df['Channel'].unique())}")
        print(f"Reagents: {len(df['Reagent'].unique())}")
        print(f"Total possible combinations: {len(df['Plastic'].unique()) * len(df['Channel'].unique()) * len(df['Reagent'].unique())}")
        print(f"Actual rows in filtered data: {len(df)}")
    if kdiffFlag: #using adjusted k, which is k minus internal control k
        dataFrameFull = pd.pivot_table(df, values='Adjusted_k', index=['Plastic', "Channel"], columns=['Reagent'])
    else: #using plain k
        dataFrameFull = pd.pivot_table(df, values='k', index=['Plastic', "Channel"], columns=['Reagent'])
    #Add Group Labels
    df_Full_Flat = dataFrameFull
    df_Full_Flat = df_Full_Flat.reset_index(0)
    df_Full_Flat = df_Full_Flat.reset_index(0)
    df_Full_Flat['Group_PN'] = df_Full_Flat['Plastic'].apply(lambda x: 'Plastic' if x[0] in ['M', 'S', 'L', 'T', 'V', 'B', 'C', 'N', 'O', 'A'] else 'Null')
    df_Full_Flat['Group_MSLVTN'] = df_Full_Flat['Plastic'].apply(
            lambda x: 'PMMA' if x[0] == "M" else ('PS' if x[0] in ['S', 'O', 'A'] else ('LDPE' if x[0] == 'L' else ('PVC' if x[0] == 'V' else ('PET' if x[0] in ['T', 'B', 'C'] else "Null"))))
    )
    df_Full_Flat['Group_Full'] = df_Full_Flat['Plastic'].apply(
            lambda x: x[0:2] if x[0] in ["M", "S", "L", "V", "T", "B", "C", "O", "A"] else ('DI' if x in ["4", "3", "2", "1"] else ('BW1' if x in ["15", "16", "17", "18"] else ('BW2' if x in ["25", "26", "27", "28"] else ('DI_O' if x in ["41", "42"] else ('DI_A' if x in ["31", "32"] else np.nan)))))
    )
    df_Full_Flat['Group_MHLN'] = df_Full_Flat['Plastic'].apply(
            lambda x: "Null" if x in ["4", "3", "2", "1", "15", "16", "17", "18", "25", "26", "27", "28", "31", "32", "41", "42"] else (
            'Medium' if x[2] == "M" else ('High' if x[2] == 'H' else ('Low' if x[2] == 'L' else np.nan)))
    )
    df_Full_Flat['Group_CSN'] = df_Full_Flat['Plastic'].apply(
        lambda x: 'Null' if x in ["4", "3", "2", "1", "15", "16", "17", "18", "25", "26", "27", "28", "31", "32", "41", "42"] else (
        'Cryo' if x[1] == "C" else ("Spherical" if x[1] == 'S' else np.nan))
    )
    df_Full_Flat['Group_Null'] = df_Full_Flat['Plastic'].apply(
            lambda x: 'DI' if x in ["4", "3", "2", "1"] else ('BW1' if x in ["15", "16", "17", "18"] else ('BW2' if x in ["25", "26", "27", "28"] else ('DI_O' if x in ["41", "42"] else ('DI_A' if x in ["31", "32"] else np.nan))))
    )
    if printFlag:
        display(df_Full_Flat)
        print(f"Unique Entries in Group_PN: {df_Full_Flat['Group_PN'].unique()}")
        print(f"Unique Entries in Group_MSLVTN: {df_Full_Flat['Group_MSLVTN'].unique()}")
        print(f"Unique Entries in Group_Full: {df_Full_Flat['Group_Full'].unique()}")
        print(f"Unique Entries in Group_MHLN: {df_Full_Flat['Group_MHLN'].unique()}")
        print(f"Unique Entries in Group_CSN: {df_Full_Flat['Group_CSN'].unique()}")
        print(f"Unique Entries in Group_Null: {df_Full_Flat['Group_Null'].unique()}")
    df_Full_Flat.columns.name = None
    return(df_Full_Flat)
#-------------------------------------------------------------------------------
def InvestigateKData(df):
    """ To look at a summary of a k_diff df """
    nan_counts_per_column = df.isna().sum()
    print("Nan per column:")
    print(nan_counts_per_column)
    categorical_cols = df.select_dtypes(include='object').columns
    numeric_cols = df.select_dtypes(include='number').columns

    # 1. Unique values in categorical columns
    print("Unique values in categorical columns:")
    for col in categorical_cols:
        print(f"{col}: {df[col].nunique()} unique values")
        print(df[col].unique())

    # 2. Summary statistics for numeric columns
    print("\nSummary statistics for numeric columns:")
    numeric_summary = df[numeric_cols].agg(['mean', 'std'])
    print(numeric_summary)

    # 3. Bar plot for k, K_IC, Adjusted_k per Plastic
    grouped = df.groupby('Plastic')[['k', 'K_IC', 'Adjusted_k']].mean().reset_index()

    # Plotting
    plt.figure(figsize=(10, 6))
    grouped_melted = grouped.melt(id_vars='Plastic', var_name='Metric', value_name='Value')

    sns.barplot(data=grouped_melted, x='Plastic', y='Value', hue='Metric')
    plt.title("Average k, K_IC, and Adjusted_k per Plastic")
    plt.ylabel("Value")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()
    return
#-------------------------------------------------------------------------------

def HoldOut(df, hold_out_percent=0.20, evenly_picked=True, e_p_col='Plastic', rs=42, printFlag=True,
            chipGroup=None):
    """
    Split the df into a set for feature selection and a set for testing

    Parameters:
    -----------
    df : pandas.DataFrame
        The input dataframe to split
    hold_out_percent : float, default=0.20
        Percentage of data to hold out for testing (0.0 to 1.0)
    evenly_picked : bool, default=True
        If True, sample evenly from each category in e_p_col
        If False, sample randomly from entire dataframe
    e_p_col : str, default='Plastic'
        Column name to use for even sampling across categories
    rs : int, default=42
        Random state for reproducible results
    printFlag : bool, default=True
        If True, print summary statistics of the split
    chipGroup : int or None, default=None
        If provided (1-4), splits by 'Channel' column instead of random/even sampling:
            Group 1 → channels 0-3  become test_df
            Group 2 → channels 4-7  become test_df
            Group 3 → channels 8-11 become test_df
            Group 4 → channels 12-15 become test_df

    Returns:
    --------
    tuple : (fs_df, test_df)
        fs_df : DataFrame for feature selection (training)
        test_df : DataFrame for testing (held out)
    """

    # --- chipGroup branch: split by Channel column ---
    if chipGroup is not None:
        channel_ranges = {
            0: range(0, 4),
            1: range(4, 8),
            2: range(8, 12),
            3: range(12, 16),
        }

        if chipGroup not in channel_ranges:
            raise ValueError(f"chipGroup must be 0, 1, 2, or 3 (got {chipGroup})")

        test_channels = list(channel_ranges[chipGroup])
        test_df = df[df['Channel'].isin(test_channels)].copy()
        fs_df   = df[~df['Channel'].isin(test_channels)].copy()

        if printFlag:
            print(f"chipGroup={chipGroup} → test channels: {test_channels}")
            print(f"Original dataset size:      {len(df)}")
            print(f"Feature selection set size: {len(fs_df)}")
            print(f"Test set size:              {len(test_df)}")
            print(f"Actual hold-out percentage: {len(test_df)/len(df):.2%}")

            print("\nChannel distribution in test set:")
            print(test_df['Channel'].value_counts().sort_index())

            if e_p_col in df.columns:
                print(f"\n{e_p_col} distribution in test set:")
                print(test_df[e_p_col].value_counts())

        return fs_df, test_df

    # --- original branch: random or evenly-picked sampling ---
    np.random.seed(rs)

    unique_vals = df[e_p_col].unique()
    print(f"Unique values in {e_p_col}: {unique_vals}")

    if evenly_picked:
        test_indices = []

        for val in unique_vals:
            category_indices = df[df[e_p_col] == val].index.tolist()
            n_to_sample = max(1, int(len(category_indices) * hold_out_percent))

            if len(category_indices) >= n_to_sample:
                sampled_indices = np.random.choice(
                    category_indices,
                    size=n_to_sample,
                    replace=False
                ).tolist()
            else:
                sampled_indices = category_indices

            test_indices.extend(sampled_indices)

    else:
        n_test = int(len(df) * hold_out_percent)
        test_indices = np.random.choice(
            df.index,
            size=n_test,
            replace=False
        ).tolist()

    test_df = df.loc[test_indices].copy()
    fs_df   = df.drop(test_indices).copy()

    if printFlag:
        print(f"Original dataset size: {len(df)}")
        print(f"Feature selection set size: {len(fs_df)}")
        print(f"Test set size: {len(test_df)}")
        print(f"Actual hold-out percentage: {len(test_df)/len(df):.2%}")

        if evenly_picked:
            print("\nDistribution in test set:")
            print(test_df[e_p_col].value_counts())
            print(f"\nPercentage from each category:")
            for val in unique_vals:
                category_total = len(df[df[e_p_col] == val])
                category_test  = len(test_df[test_df[e_p_col] == val])
                if category_total > 0:
                    pct = category_test / category_total
                    print(f"{val}: {category_test}/{category_total} ({pct:.2%})")

    return fs_df, test_df
#-------------------------------------------------------------------------------
def CMBuilder(group_name, df_entire, model_list, save_csv_path, kernelType,
                                randomState=42, dataType='k',
                                printFlag=True, save_results=False,
                                result_filename=None, test_flag=False,
                                swapLabel=False, chipSplit=False, chipGroup=0, all_model_flag=False,
                                **model_kwargs):
    """ CMBuilder builds confusion matrices after optimal models have been found """
    if all_model_flag:
        model_list = ["SVM", "LR", "LDA"]
    CSV_COLUMNS = ["model", "group_name", "hold_out_chip", "val_chip", "best_val", "best_features", "val_test", "kernel_type", "CM", "CM_labels"]
    MODEL_FUNCTIONS = {
        'SVM': RunSVM,
        'LDA': RunLDA,
        'LR': RunLR,
    }
    if group_name == 'Group_PN':
        metric = 'f1_score'
        f1Flag = True
    elif group_name == 'Group_Full':
        metric = 'accuracy'
        f1Flag = False
    elif group_name == 'Group_MHLN':
        metric = 'accuracy'
        f1Flag = False
    existing_results = load_existing_results(save_csv_path)
    print(f"Loaded {len(existing_results)} existing results from CSV")
    for model in model_list:
        model_func = MODEL_FUNCTIONS[model]

        # Run both kernels for SVM when all_model_flag is set, otherwise just the passed kernelType
        if model == "SVM" and all_model_flag:
            kernel_types = ["linear", "rbf"]
        else:
            kernel_types = [kernelType]

        for kt in kernel_types:
            print(f"Running {group_name} for {model} {kt}")
            for hold_out_chip in [0, 1, 2, 3]:  # per hold out data split
                df, df_test = HoldOut(df_entire, chipGroup=hold_out_chip, printFlag=False)
                val_results_metric = []
                val_results_features = []
                for val_chip in [0, 1, 2, 3]:  # per validation data split
                    if val_chip == hold_out_chip:
                        continue
                    key = (str(model), str(group_name), str(hold_out_chip), str(val_chip), str(kt))
                    if key in existing_results:
                        print(f"Skipping {model} {group_name} hold_out={hold_out_chip} val={val_chip}, kernel={kt} (already done)")
                        continue
                    best_val, best_features = GridSearchFeatureSelection(group_name, df, model_func, 1, 17, val_chip=val_chip, kernelType=kt, printFlag=False)
                    val_results_metric.append(best_val)
                    val_results_features.append(best_features)
                    print(f"Best validation metric value for {model} {group_name} hold out ({hold_out_chip}) val ({val_chip}) : {best_val}")
                    print(f"Combined unique strings: {best_features}")
                    all_columns = df.columns.tolist()
                    groups_list = [item for item in all_columns if item.startswith("Group")]
                    total_col = list(["Channel", "Plastic"]) + best_features + groups_list
                    df_test_use = df_test[total_col].copy()
                    results = model_func(group_name=group_name, df=df, randomState=randomState,
                        dataType=dataType, printFlag=False, featureAnalysisFlag=False,
                        BICFlag=False, f1Flag=f1Flag, cmFlag=True, kernelType=kt,
                        swapLabel=False, df_test=df_test_use, chipSplit=None)
                    val_test = results[metric]
                    cm = results["CM"]
                    cm_labels = results["cm_labels"]
                    print(f"Labels are {cm_labels}")
                    row = {
                        "Model": model,
                        "Group_Name": group_name,
                        "Hold_Chip": hold_out_chip,
                        "Val_Chip": val_chip,
                        "Best_Val": best_val,
                        "Features": best_features,
                        "Test_Metric": val_test,
                        "Kernel_Type": kt,
                        "CM": cm,
                        "CM_labels": cm_labels
                    }
                    write_result(save_csv_path, row)
                    existing_results.add(key)
    return None
#-------------------------------------------------------------------------------


import argparse
def run_function(Question, savePath):
    print(f"Running with Question={Question}, savePath={savePath}")
    FilePath = '/home/u20/lexideford/MNP_Detection_Rev1/20251104KH_combined.csv' #constant
    save_csv_path=savePath
    if Question == "Detection":
        plastic_list = ['MCH', 'MCM', 'MCL', 'SCH', 'SCM', 'SCL', 'VCH', 'VCM', 'VCL', 'LCH', 'LCM', 'LCL', 'TCH', 'TCM', 'TCL', '1', '2', '3', '4']
        group_name = 'Group_PN'
        model = ["SVM"]
        kernelType = "rbf"
    elif Question == "Type":
        group_name = 'Group_Full'
        plastic_list = ['MCH', 'MCM', 'MCL', 'SCH', 'SCM', 'SCL', 'VCH', 'VCM', 'VCL', 'LCH', 'LCM', 'LCL', 'TCH', 'TCM', 'TCL', '1', '2', '3', '4']
        model = ["SVM"]
        kernelType = "rbf"
    elif Question == "BW":
        group_name = 'Group_Full'
        plastic_list = ['BCH', 'BCM', 'BCL', 'CCH', 'CCM', 'CCL', '15', '16', '17', '18', '25', '26', '27', '28']
        model = ["LDA"]
        kernelType = "rbf"
    elif Question == "CB":
        group_name = 'Group_PN'
        plastic_list = ['41', '42', 'OCH', 'OCM', 'OCL']
        model = ["SVM"]
        kernelType = "rbf"
    elif Question == "AS":
        group_name = 'Group_PN'
        plastic_list = ['31', '32', 'ACH', 'ACM', 'ACL']
        model = ["LR"]
        kernelType = "rbf"
    elif Question == "LC":
        group_name = 'Group_PN'
        plastic_list = ['NSA', 'NSB', 'NSC', '1', '2']
        model = ["SVM"]
        kernelType = "rbf"
    elif Question == "Type_NoDI":
        group_name = 'Group_Full'
        plastic_list = ['MCH', 'MCM', 'MCL', 'SCH', 'SCM', 'SCL', 'VCH', 'VCM', 'VCL', 'LCH', 'LCM', 'LCL', 'TCH', 'TCM', 'TCL']
        model = ["SVM"]
        kernelType = "rbf"
    elif Question == "NS":
        group_name = 'Group_PN'
        plastic_list = ['MSH', 'MSM', 'MSL', 'SSH', 'SSM', 'SSL', '1', '2', '3', '4']
        model = ["LR"]
        kernelType = "rbf"
    elif Question == "CON":
        group_name = 'Group_MHLN'
        plastic_list = ['MCH', 'MCM', 'MCL', 'SCH', 'SCM', 'SCL', 'VCH', 'VCM', 'VCL', 'LCH', 'LCM', 'LCL', 'TCH', 'TCM', 'TCL', '1', '2', '3', '4']
        model = ["LR"]
        kernelType = "rbf"
    elif Question == "CON_NoDI":
        group_name = 'Group_MHLN'
        plastic_list = ['MCH', 'MCM', 'MCL', 'SCH', 'SCM', 'SCL', 'VCH', 'VCM', 'VCL', 'LCH', 'LCM', 'LCL', 'TCH', 'TCM', 'TCL']
        model = ["LR"]
        kernelType = "rbf"
    elif Question == "BW_2":
        group_name = 'Group_PN'
        plastic_list = ['BCH', 'BCM', 'BCL', 'CCH', 'CCM', 'CCL', '15', '16', '17', '18', '25', '26', '27', '28']
        model = ["SVM"]
        kernelType = "rbf"

    df = WrangleKData(FilePath, printFlag=False, kdiffFlag=False, selectedPlasticsList = plastic_list)
    CMBuilder(group_name, df, model, save_csv_path, kernelType, all_model_flag=True)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--question", type=str, required=True,
                         choices=["Detection","Type","BW","CB","AS","LC","Type_NoDI","NS", "CON", "CON_NoDI", "BW_2"])
    parser.add_argument("--savepath", type=str, required=True)
    args = parser.parse_args()
    run_function(args.question, args.savepath)